[package]
name = "scriptbots-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
duckdb = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
scriptbots-core = { path = "../scriptbots-core" }
