[package]
name = "scriptbots-index"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]

[lints]
workspace = true
