[package]
name = "scriptbots-app"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
scriptbots-brain = { path = "../scriptbots-brain" }
scriptbots-brain-ml = { path = "../scriptbots-brain-ml", optional = true }
scriptbots-core = { path = "../scriptbots-core" }
scriptbots-render = { path = "../scriptbots-render" }
scriptbots-storage = { path = "../scriptbots-storage" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
default = []
ml = ["scriptbots-brain-ml"]
