[package]
name = "scriptbots-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
slotmap = { workspace = true }
rand = { workspace = true }
